import type { Metadata } from "next";
import Common from "./(components)/common";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          <Common />
          {children}
        </div>
      </body>
    </html>
  );
}
