import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import {
  poppinsBold,
  poppinsMedium,
  poppinsSemiBold,
  poppinsRegular,
} from "./fonts";
import { AuthContextProvider } from "@/context/authContext";
import { Suspense } from "react";
import Loader from "./loader";

export const metadata: Metadata = {
  title: "Store it",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsBold.variable} ${poppinsSemiBold.variable} ${poppinsMedium.variable} ${poppinsRegular.variable}`}
      >
        <Suspense fallback={<Loader />}>
          <AuthContextProvider> {children}</AuthContextProvider>
        </Suspense>
      </body>
    </html>
  );
}
